### ISSUE TITLE
Collapsing the content of moment + being able to see multiple descriptions

### ISSUE THREAD

**Issue by yprie** [yprie/uPMT#27]
Feature request.

**Comment by Thykof** [comment]
I have created a new pre-release here: https://github.com/Thykof/uPMT/releases/tag/POC27-1 that allow to collapse the content of a moment.

**Comment by buscon** [comment]
hi @Thykof ,

thanks for the pre-release!
It works as expected, but the descripteme in the moments are much shorter than in the official version. I would rather keep them with the same length of the moment box, no?

**Comment by Thykof** [comment]
Can you provide screenshots? I can't see any difference about the width of the moments.

**Comment by buscon** [comment]
sure, here they are.

![full_length](https://user-images.githubusercontent.com/2972257/92941411-9f931900-f450-11ea-851b-c50c6c4776d1.png)
![short_descripteme](https://user-images.githubusercontent.com/2972257/92941415-a02baf80-f450-11ea-98ab-98c4bf2e8439.png)

**Comment by yprie** [comment]
Question is also what remains in the collapsed moment: here it hides the categories, but keeps the descriptemes for the moment. We could imagine it only shows the name of the contained categories (eg a set of named / colored boxes), or others "reduced views of moments", which at some point may be the most important information.

**Comment by yprie** [comment]
I was no clear, there are different descriptemes "attached" to moments: descriptemes that justify 1/ moments as such  2/ categories as such and 3/ properties as such + their values. So when shrinking a moment we could choose to discard or keep any of them. 

My feeling is that the most important items to keep when shrinking are the categories' names, that are a good summary of the modelling.

**Comment by buscon** [comment]
> Question is also what remains in the collapsed moment: here it hides the categories, but keeps the descriptemes for the moment. We could imagine it only shows the name of the contained categories (eg a set of named / colored boxes), or others "reduced views of moments", which at some point may be the most important information.

my screenshot created confusion, I confirm what @Thykof said, it hides the comment, the descriptemes and the categories. Only the title of the moment is shown.

> > I would rather keep them with the same length of the moment box, no?
> 
> Right, I accidentally added a bug, just fixed here : https://github.com/Thykof/uPMT/releases/tag/POC27-2

I cannot unzip the file.

**Comment by buscon** [comment]
> I was no clear, there are different descriptemes "attached" to moments: descriptemes that justify 1/ moments as such 2/ categories as such and 3/ properties as such + their values. So when shrinking a moment we could choose to discard or keep any of them.
> 
> My feeling is that the most important items to keep when shrinking are the categories' names, that are a good summary of the modelling.

I agree with what you suggest, the title of the moment and the category names are a good summary.

**Comment by Thykof** [comment]
> I cannot unzip the file.

Fixed, I have re-upload the zip files

**Comment by buscon** [comment]
> > I cannot unzip the file.
> 
> Fixed, I have re-upload the zip files

thank you!
I confirm that it works as expected. 
It would be great to have an extra button to toggle the hide/show of all the moments at once, if it is not too much work on your side.

**Comment by Thykof** [comment]
> I agree with what you suggest, the title of the moment and the category names are a good summary.

Noted. It may need deeper changes in the code (to keep the code maintainable).

>  It would be great to have an extra button to toggle the hide/show of all the moments at once, if it is not too much work on your side.

Ok, add a "View" menu between "File" and "Edit" and button in that menu "Collapse all moments"?

Another question, would you want the software to remember what moments are hidden at the close of the app, and when opening again the app, hide the moment that were hidden at the close?

**Comment by buscon** [comment]
> > I agree with what you suggest, the title of the moment and the category names are a good summary.
> 
> Noted. It may need deeper changes in the code (to keep the code maintainable).

ok, thank you!

> > It would be great to have an extra button to toggle the hide/show of all the moments at once, if it is not too much work on your side.
> 
> Ok, add a "View" menu between "File" and "Edit" and button in that menu "Collapse all moments"?

It sounds reasonable to be, I guess @yprie should decide.

> Another question, would you want the software to remember what moments are hidden at the close of the app, and when opening again the app, hide the moment that were hidden at the close?

This sounds reasonable too to me.

**Comment by yprie** [comment]
Ok for the View menu, this is standard.

For the "collapse all" command, let's put it there. If there is a need  for a button later it will be easy to add,

**Comment by Thykof** [comment]
Hello,

In this pre-release https://github.com/Thykof/uPMT/releases/tag/POC27-3: 
 - save the state of each moment: collapsed or not.
 - add the button "Collapse all moments" in View menu

**Comment by buscon** [comment]
hi,

the behavior you described works as expected.
One question though: I thought that @yprie and me agreed on hiding only the descriptemes and the comments and to leave the title and the categories. Can you maybe change the behavior of the hiding/showing in such a way?

Thanks!

**Comment by Thykof** [comment]
Hi,

I will try, this is my objective for this week.

**Comment by Thykof** [comment]
here it is: https://github.com/Thykof/uPMT/releases/tag/POC27-4

**Comment by buscon** [comment]
hi @Thykof ,

thanks for the new release!
two comments:

1.  when the moments are collapsed (closed), they should show not only the category name but also the properties. This is my personal opinion.
2.  the radio button in the view menu "collapse all moments" should work both ways: collapse all moments or open all moments.

**Comment by yprie** [comment]
Hello.

 > when the moments are collapsed (closed), they should show not only the category name but also the properties. This is my personal opinion.

 I guess this is something that could be controllable: "Show properties". 

We could also only show the properties that are associated to values (or which have associated descriptemes). 

This is clearly something we have to experiment with real data, as what we show participates to how people.

> the radio button in the view menu "collapse all moments" should work both ways: collapse all moments or open all moments.

Yes.

**Comment by buscon** [comment]
hi!

> > when the moments are collapsed (closed), they should show not only the category name but also the properties. This is my personal opinion.
> 
> I guess this is something that could be controllable: "Show properties".
> 
> We could also only show the properties that are associated to values (or which have associated descriptemes).


totally agree with your suggestions: with having an extra choice whether to show the properties or not OR to show only the properties which have a value.

> This is clearly something we have to experiment with real data, as what we show participates to how people.

Right now four people in my team they are using the software, so I can report how they deal with such selection. In the next months, two more people are joining the team.

**Comment by Thykof** [comment]
Hi

I will focus on this for now :

> the radio button in the view menu "collapse all moments" should work both ways: collapse all moments or open all moments.

**Comment by buscon** [comment]
hi @Thykof ,

I tested the last release, the "Open all moments" button opens and closes all moments as it should.
Thanks!

**Comment by yprie** [comment]
Should we close the issue?

**Comment by Thykof** [comment]
I will close it with the merge to this repo (coming very soon)

**Comment by Thykof** [comment]
Here is the final release: https://github.com/yprie/uPMT/releases/tag/v0.4.1
