### ISSUE TITLE
Feature request: show which moments are using a property

### ISSUE THREAD

**Issue by buscon** [yprie/uPMT#47]
It would be useful to have an overview of which moments are using a certain property of a category.
Right now it is only possible to see how many moments are using a certain property but it is not possible to know which moments are using it.

**Comment by yprie** [comment]
Yes, the current indicator (how many moments use) is just there to show the architecture to get the information on the use of categories is ok. Now work has to be done to figure out what has to be shown, and how.

**Comment by yprie** [comment]
Cf. uses of categories, but with their valued properties
