### ISSUE TITLE
Feature requests: colors for each moment and each category.

### ISSUE THREAD

**Issue by buscon** [yprie/uPMT#48]
It would be very useful to be able to set colors for moments and properties.

**Comment by yprie** [comment]
Well, color was possible for moments and categories in earlier versions, it should come back.

How would you color properties?

**Comment by buscon** [comment]
> Well, color was possible for moments and categories in earlier versions, it should come back.

great, good to know :)

> How would you color properties?

actually that was a mistake of mine, I meant colors for each moment and category. I do not think we need colors for properties.
I corrected the title of this feature request.

**Comment by yvesmotteux** [comment]
Hello, I'm Yves, one of the two students working on this project this year. We're working to implement the color changes, and I wanted to show you a couple of mockups to know what you think about them and if we should do something differently (the color choices are not definitive of course, I filled them randomly).

The first image shows how you would change and previsualize  the color of a category, and the second picture shows how you would change the color of a moment.
![image](https://user-images.githubusercontent.com/72164541/100477376-70ec1c80-30e8-11eb-9d02-fc34e86eae30.png)
![image](https://user-images.githubusercontent.com/72164541/100477709-7302ab00-30e9-11eb-8e36-058e4ffce449.png)

**Comment by yprie** [comment]
@buscon ?

**Comment by buscon** [comment]
dear @yvesmotteux ,

sorry for my late answer. 
Thanks a lot for these color suggestions, they look pretty good to me.
As soon as you have a testing version, I am happy to give it a try.

**Comment by buscon** [comment]
dear @yvesmotteux 

any news about this feature?
from the images above, it looked like you already implemented. if there is a release version to test, I can do it.

**Comment by yvesmotteux** [comment]
hello @buscon 
I implemented the colors of moments and categories in this build : https://github.com/yvesmotteux/uPMT/releases/tag/4d05ba8
feel free to try it and tell me if anything seems to be out of place. If you think the colour choice is odd, don't hesitate to suggest modifications

**Comment by buscon** [comment]
hi @yvesmotteux,

thanks for your work and sorry for my late answer.

I just tested the build, yes, it works pretty nicely, thank you very much!

for what concerns me the issue can be closed.
