### ISSUE TITLE
Feature Request: transitional events representation

### ISSUE THREAD

**Issue by buscon** [yprie/uPMT#54]
hi all,

based on this paper of C. Petitmengin et . al:
https://link.springer.com/article/10.1007%2Fs11097-018-9597-4
Transitional events are "Modification in the subject’s experience which in turn induces significant transformations in his/her experience."

Such transitional events, could be represented as a dotted line that separates the moment over time, as they did in this paper:
https://constructivist.info/14/2/123.valenzuela
As the paper is not freely available, I post a picture of how they represented the transitional evens (they call them hinge points but it is the same thing)
![Screenshot from 2020-12-16 11-33-10](https://user-images.githubusercontent.com/2972257/102337435-c0f52b00-3f92-11eb-97cd-fc11899e927e.png)

What do you think about adding such a feature?

**Comment by yprie** [comment]
Hi Marcello. We discussed his issue recently. For us, the most easy way to do so is to be able to turn any moment (provided is has no submoment), into a "transitional event (moment)", which will have the effect of changing its presentation + adding a vertical line under it. This would allow to separate phases on the first level, but also subphases at any level, as well as to justify the event with descriptemes (as for any moment). Such "transitional event moments" could be toggled back as normal moment at any time if needed.

**Comment by buscon** [comment]
hi @yprie ,

thanks for your answer, your suggestion makes sense to me. I am happy to test as soon as there is a testing release.

**Comment by yvesmotteux** [comment]
hello @buscon ,
I implemented a first version of this feature, available here : https://github.com/yvesmotteux/uPMT/releases/tag/a820c4c 
If you have time to test it and report me any problem with it, it would help me a lot!

things that should be changed quickly : 
- gray scale that goes too dark
- the lines that don't stop at the same level

**Comment by buscon** [comment]
Dear @yvesmotteux ,

thanks for your work and testing version!
I will test it in the next days and report back.

**Comment by buscon** [comment]
dear @yvesmotteux 

I tested your version and yes, it works and looks good. Thank you!

I agree with your comments, the grey color is too dark and the lines should go a bit further.
