### ISSUE TITLE
Feature request: copy text from interview transcript window

### ISSUE THREAD

**Issue by buscon** [yprie/uPMT#55]
The text in the interview transcript window cannot be copied.
It should not be hard to make copyable.

Thank you.

**Comment by Thykof** [comment]
Hi @buscon , 
I have added a menu on right click when we select a text in the transcript.
You can try be downloading the build here: https://github.com/Thykof/uPMT/releases/tag/5702c7d

**Comment by buscon** [comment]
hi @Thykof ,

the copying work, even using the Ctrl+C shortcut.

What is a bit awkward: if the text is already underlined with one color, you cannot select it and therefore you cannot copy it either.
But I guess this is a bit different issue, so we can close this feature request, so far it concerns me.

Thank you!
