### ISSUE TITLE
Feature request: size of the interview transcript window

### ISSUE THREAD

**Issue by buscon** [yprie/uPMT#56]
The window with the interview transcript can be only partially resized.
Especially in the first part of the analysis or anytime when you want to focus on the transcript and mark the text, it would be very useful to be able to enlarge such window, even making it full window if possible.
Right now the enlargement is blocked to a certain size.

Thank you.

**Comment by yprie** [comment]
Hi @buscon, the last pre-release version should solve this problem, allowing full resize. You can also collapse the transcription view, or alternatively the experience description view. Please try and comment.

**Comment by buscon** [comment]
hi @yprie ,

I tested the resize with the 91a9653 pre-release but the behaviour did not change.
Should I maybe use another release?

**Comment by gabikun** [comment]
Hello, this should be solved in version 0.6. I will close this issue if it's ok for you.
