### ISSUE TITLE
Feature request: Undo shortcut as Ctrl+Z for English language

### ISSUE THREAD

**Issue by buscon** [yprie/uPMT#57]
Is it possible to add an Undo function?
Possibly with the standard keyboard shortcut Ctrl+Z

Thank you.

**Comment by yprie** [comment]
It seems to me there already is a working Undo function.

**Comment by buscon** [comment]
You are right!
It is only with Ctrl+W shortcut, probably because of the french layout.
Ctrl+Z would be better when you switch to English, but I see it as a "nice-to-have".

**Comment by yprie** [comment]
Oh, so he undo is mapped on a key position, and not on its content...
Maybe rename the thread then to have CRL/Z work on various keyboards.

Also, undo is accessible in the Menu

**Comment by buscon** [comment]
done :)

Thanks for your quick answers.
