### ISSUE TITLE
Being able to merge moment(s) by drag & drop 

### ISSUE THREAD

**Issue by RomanMalopsy** [yprie/uPMT#68]
Actually, we're not able to drag moment into another one. We need to drag and drop each and every descripteme to the other moment. It might be easier to drag & drop whole moment, especially with lots of sentences. 

I add to this request a screen to improve the understanding of this request. 

<img width="578" alt="Capture d’écran 2021-12-10 à 16 03 38" src="https://user-images.githubusercontent.com/95926431/145597106-00cd8e35-acc2-4042-8fa6-da6bda85662d.png">

**Comment by yprie** [comment]
The descriptemes and categories of the dropped moment should be added to the moment where it is dropped. 

If there is any ambiguity (eg. 2 same categories), then ask what to do.

**Comment by gabikun** [comment]
Hello, this should be solved in version 0.6. I will close this issue if it's ok for you.
